// Mocks generated by Mockito 5.4.4 from annotations
// in my_project_name/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:convert' as _i30;
import 'dart:typed_data' as _i31;

import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i8;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:my_project_name/core/error/failure.dart' as _i11;
import 'package:my_project_name/core/network/network_info.dart' as _i23;
import 'package:my_project_name/features/authentication/data/model/get_me_response_model.dart'
    as _i3;
import 'package:my_project_name/features/authentication/data/model/login_response_model.dart'
    as _i19;
import 'package:my_project_name/features/authentication/data/model/signup_response_model.dart'
    as _i18;
import 'package:my_project_name/features/authentication/data/model/token_taker_model.dart'
    as _i4;
import 'package:my_project_name/features/authentication/data/resource/auth_local_data_source.dart'
    as _i15;
import 'package:my_project_name/features/authentication/data/resource/auth_remote_data_source.dart'
    as _i17;
import 'package:my_project_name/features/authentication/domain/entity/getme_entity.dart'
    as _i14;
import 'package:my_project_name/features/authentication/domain/entity/login_entity.dart'
    as _i12;
import 'package:my_project_name/features/authentication/domain/entity/signup_entity.dart'
    as _i13;
import 'package:my_project_name/features/authentication/domain/repositories/auth_repository.dart'
    as _i9;
import 'package:my_project_name/features/eCommerce/data/data_sources/local_data_source.dart'
    as _i22;
import 'package:my_project_name/features/eCommerce/data/data_sources/remote_data_source.dart'
    as _i21;
import 'package:my_project_name/features/eCommerce/data/models/product_model.dart'
    as _i5;
import 'package:my_project_name/features/eCommerce/domain/entities/product.dart'
    as _i20;
import 'package:my_project_name/features/eCommerce/domain/repositories/product_repository.dart'
    as _i7;
import 'package:my_project_name/features/eCommerce/domain/usecases/add_product.dart'
    as _i29;
import 'package:my_project_name/features/eCommerce/domain/usecases/delete_product.dart'
    as _i28;
import 'package:my_project_name/features/eCommerce/domain/usecases/edit_product.dart'
    as _i27;
import 'package:my_project_name/features/eCommerce/domain/usecases/get_all_product.dart'
    as _i26;
import 'package:my_project_name/features/eCommerce/domain/usecases/get_current_product.dart'
    as _i25;
import 'package:shared_preferences/shared_preferences.dart' as _i24;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetMeResponseModel_1 extends _i1.SmartFake
    implements _i3.GetMeResponseModel {
  _FakeGetMeResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTokenTakerModel_2 extends _i1.SmartFake
    implements _i4.TokenTakerModel {
  _FakeTokenTakerModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductModel_3 extends _i1.SmartFake implements _i5.ProductModel {
  _FakeProductModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_4 extends _i1.SmartFake implements Duration {
  _FakeDuration_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddressCheckResult_5 extends _i1.SmartFake
    implements _i6.AddressCheckResult {
  _FakeAddressCheckResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductRepository_6 extends _i1.SmartFake
    implements _i7.ProductRepository {
  _FakeProductRepository_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_7 extends _i1.SmartFake implements _i8.Response {
  _FakeResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_8 extends _i1.SmartFake
    implements _i8.StreamedResponse {
  _FakeStreamedResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, void>> login(_i12.LoginEntity? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [user],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, void>>.value(
            _FakeEither_0<_i11.Failure, void>(
          this,
          Invocation.method(
            #login,
            [user],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, void>> signUp(_i13.SignUpEntity? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [user],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, void>>.value(
            _FakeEither_0<_i11.Failure, void>(
          this,
          Invocation.method(
            #signUp,
            [user],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, void>>.value(
            _FakeEither_0<_i11.Failure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i14.GetMeEntity>> getMe() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMe,
          [],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i14.GetMeEntity>>.value(
                _FakeEither_0<_i11.Failure, _i14.GetMeEntity>(
          this,
          Invocation.method(
            #getMe,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i14.GetMeEntity>>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i15.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #getToken,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> cacheToken(_i4.TokenTakerModel? tokenToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheToken,
          [tokenToCache],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i17.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i3.GetMeResponseModel> getMe(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMe,
          [token],
        ),
        returnValue:
            _i10.Future<_i3.GetMeResponseModel>.value(_FakeGetMeResponseModel_1(
          this,
          Invocation.method(
            #getMe,
            [token],
          ),
        )),
      ) as _i10.Future<_i3.GetMeResponseModel>);

  @override
  _i10.Future<void> signUp(_i18.SignupResponseModel? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [user],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i4.TokenTakerModel> login(_i19.LoginResponseModel? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [user],
        ),
        returnValue:
            _i10.Future<_i4.TokenTakerModel>.value(_FakeTokenTakerModel_2(
          this,
          Invocation.method(
            #login,
            [user],
          ),
        )),
      ) as _i10.Future<_i4.TokenTakerModel>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i7.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i20.ProductEntity>> getCurrentProduct(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentProduct,
          [productId],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i20.ProductEntity>>.value(
                _FakeEither_0<_i11.Failure, _i20.ProductEntity>(
          this,
          Invocation.method(
            #getCurrentProduct,
            [productId],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i20.ProductEntity>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, void>> addProduct(
          _i20.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [product],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, void>>.value(
            _FakeEither_0<_i11.Failure, void>(
          this,
          Invocation.method(
            #addProduct,
            [product],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, void>> deleteProduct(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productId],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, void>>.value(
            _FakeEither_0<_i11.Failure, void>(
          this,
          Invocation.method(
            #deleteProduct,
            [productId],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, void>> editProduct(
          _i20.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProduct,
          [product],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, void>>.value(
            _FakeEither_0<_i11.Failure, void>(
          this,
          Invocation.method(
            #editProduct,
            [product],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i20.ProductEntity>>>
      getAllProducts() => (super.noSuchMethod(
            Invocation.method(
              #getAllProducts,
              [],
            ),
            returnValue: _i10.Future<
                    _i2.Either<_i11.Failure, List<_i20.ProductEntity>>>.value(
                _FakeEither_0<_i11.Failure, List<_i20.ProductEntity>>(
              this,
              Invocation.method(
                #getAllProducts,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i20.ProductEntity>>>);
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i21.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i5.ProductModel> getCurrentProduct(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentProduct,
          [productId],
        ),
        returnValue: _i10.Future<_i5.ProductModel>.value(_FakeProductModel_3(
          this,
          Invocation.method(
            #getCurrentProduct,
            [productId],
          ),
        )),
      ) as _i10.Future<_i5.ProductModel>);

  @override
  _i10.Future<void> addProduct(_i5.ProductModel? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [product],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteProduct(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> editProduct(_i5.ProductModel? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProduct,
          [product],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i5.ProductModel>> getAllProducts() => (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
        ),
        returnValue:
            _i10.Future<List<_i5.ProductModel>>.value(<_i5.ProductModel>[]),
      ) as _i10.Future<List<_i5.ProductModel>>);
}

/// A class which mocks [ProductLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i22.ProductLocalDataSource {
  MockProductLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i5.ProductModel>> getAllProducts() => (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
        ),
        returnValue:
            _i10.Future<List<_i5.ProductModel>>.value(<_i5.ProductModel>[]),
      ) as _i10.Future<List<_i5.ProductModel>>);

  @override
  _i10.Future<void> cacheAllProducts(List<_i5.ProductModel>? producToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAllProducts,
          [producToCache],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i23.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
}

/// A class which mocks [InternetConnectionChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnectionChecker extends _i1.Mock
    implements _i6.InternetConnectionChecker {
  MockInternetConnectionChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get checkInterval => (super.noSuchMethod(
        Invocation.getter(#checkInterval),
        returnValue: _FakeDuration_4(
          this,
          Invocation.getter(#checkInterval),
        ),
      ) as Duration);

  @override
  Duration get checkTimeout => (super.noSuchMethod(
        Invocation.getter(#checkTimeout),
        returnValue: _FakeDuration_4(
          this,
          Invocation.getter(#checkTimeout),
        ),
      ) as Duration);

  @override
  List<_i6.AddressCheckOptions> get addresses => (super.noSuchMethod(
        Invocation.getter(#addresses),
        returnValue: <_i6.AddressCheckOptions>[],
      ) as List<_i6.AddressCheckOptions>);

  @override
  set addresses(List<_i6.AddressCheckOptions>? value) => super.noSuchMethod(
        Invocation.setter(
          #addresses,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<bool> get hasConnection => (super.noSuchMethod(
        Invocation.getter(#hasConnection),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i6.InternetConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatus),
        returnValue: _i10.Future<_i6.InternetConnectionStatus>.value(
            _i6.InternetConnectionStatus.connected),
      ) as _i10.Future<_i6.InternetConnectionStatus>);

  @override
  _i10.Stream<_i6.InternetConnectionStatus> get onStatusChange =>
      (super.noSuchMethod(
        Invocation.getter(#onStatusChange),
        returnValue: _i10.Stream<_i6.InternetConnectionStatus>.empty(),
      ) as _i10.Stream<_i6.InternetConnectionStatus>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool get isActivelyChecking => (super.noSuchMethod(
        Invocation.getter(#isActivelyChecking),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<_i6.AddressCheckResult> isHostReachable(
          _i6.AddressCheckOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #isHostReachable,
          [options],
        ),
        returnValue:
            _i10.Future<_i6.AddressCheckResult>.value(_FakeAddressCheckResult_5(
          this,
          Invocation.method(
            #isHostReachable,
            [options],
          ),
        )),
      ) as _i10.Future<_i6.AddressCheckResult>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i24.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i10.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [GetCurrentProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentProductUsecase extends _i1.Mock
    implements _i25.GetCurrentProductUsecase {
  MockGetCurrentProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_6(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i7.ProductRepository);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i20.ProductEntity>> call(
          _i25.CurrentParams? currentParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [currentParams],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i20.ProductEntity>>.value(
                _FakeEither_0<_i11.Failure, _i20.ProductEntity>(
          this,
          Invocation.method(
            #call,
            [currentParams],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i20.ProductEntity>>);
}

/// A class which mocks [GetAllProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllProductUsecase extends _i1.Mock
    implements _i26.GetAllProductUsecase {
  MockGetAllProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_6(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i7.ProductRepository);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i20.ProductEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i10
            .Future<_i2.Either<_i11.Failure, List<_i20.ProductEntity>>>.value(
            _FakeEither_0<_i11.Failure, List<_i20.ProductEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i20.ProductEntity>>>);
}

/// A class which mocks [EditProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProductUsecase extends _i1.Mock
    implements _i27.EditProductUsecase {
  MockEditProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_6(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i7.ProductRepository);

  @override
  _i10.Future<_i2.Either<_i11.Failure, void>> call(
          _i27.EditParams? editparams) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [editparams],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, void>>.value(
            _FakeEither_0<_i11.Failure, void>(
          this,
          Invocation.method(
            #call,
            [editparams],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, void>>);
}

/// A class which mocks [DeleteProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProductUsecase extends _i1.Mock
    implements _i28.DeleteProductUsecase {
  MockDeleteProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_6(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i7.ProductRepository);

  @override
  _i10.Future<_i2.Either<_i11.Failure, void>> call(
          _i28.DeleteParams? deleteparams) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [deleteparams],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, void>>.value(
            _FakeEither_0<_i11.Failure, void>(
          this,
          Invocation.method(
            #call,
            [deleteparams],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, void>>);
}

/// A class which mocks [AddProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddProductUsecase extends _i1.Mock implements _i29.AddProductUsecase {
  MockAddProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_6(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i7.ProductRepository);

  @override
  _i10.Future<_i2.Either<_i11.Failure, void>> call(_i29.AddParams? addparams) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [addparams],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, void>>.value(
            _FakeEither_0<_i11.Failure, void>(
          this,
          Invocation.method(
            #call,
            [addparams],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, void>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i8.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i8.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i30.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i30.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i30.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i30.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i31.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<_i31.Uint8List>.value(_i31.Uint8List(0)),
      ) as _i10.Future<_i31.Uint8List>);

  @override
  _i10.Future<_i8.StreamedResponse> send(_i8.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i10.Future<_i8.StreamedResponse>.value(_FakeStreamedResponse_8(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i10.Future<_i8.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
