// Mocks generated by Mockito 5.4.4 from annotations
// in my_project_name/test/features/eCommerce/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i13;
import 'dart:typed_data' as _i15;

import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:my_project_name/core/error/failure.dart' as _i10;
import 'package:my_project_name/core/platform/network_info.dart' as _i6;
import 'package:my_project_name/features/eCommerce/data/data_sources/local_data_source.dart'
    as _i5;
import 'package:my_project_name/features/eCommerce/data/data_sources/remote_data_source.dart'
    as _i4;
import 'package:my_project_name/features/eCommerce/data/models/product_model.dart'
    as _i3;
import 'package:my_project_name/features/eCommerce/data/repositories/product_repository_impl.dart'
    as _i12;
import 'package:my_project_name/features/eCommerce/domain/entities/product.dart'
    as _i11;
import 'package:my_project_name/features/eCommerce/domain/repositories/product_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductModel_1 extends _i1.SmartFake implements _i3.ProductModel {
  _FakeProductModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductRemoteDataSource_2 extends _i1.SmartFake
    implements _i4.ProductRemoteDataSource {
  _FakeProductRemoteDataSource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductLocalDataSource_3 extends _i1.SmartFake
    implements _i5.ProductLocalDataSource {
  _FakeProductLocalDataSource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworkInfo_4 extends _i1.SmartFake implements _i6.NetworkInfo {
  _FakeNetworkInfo_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_5 extends _i1.SmartFake implements _i7.Response {
  _FakeResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_6 extends _i1.SmartFake
    implements _i7.StreamedResponse {
  _FakeStreamedResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i8.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>> getCurrentProduct(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentProduct,
          [productId],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>>.value(
                _FakeEither_0<_i10.Failure, _i11.ProductEntity>(
          this,
          Invocation.method(
            #getCurrentProduct,
            [productId],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, void>> addProduct(
          _i11.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [product],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, void>>.value(
            _FakeEither_0<_i10.Failure, void>(
          this,
          Invocation.method(
            #addProduct,
            [product],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, void>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, void>> deleteProduct(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productId],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, void>>.value(
            _FakeEither_0<_i10.Failure, void>(
          this,
          Invocation.method(
            #deleteProduct,
            [productId],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, void>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, void>> editProduct(
          _i11.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProduct,
          [product],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, void>>.value(
            _FakeEither_0<_i10.Failure, void>(
          this,
          Invocation.method(
            #editProduct,
            [product],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, void>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.ProductEntity>>>
      getAllProducts() => (super.noSuchMethod(
            Invocation.method(
              #getAllProducts,
              [],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure, List<_i11.ProductEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.ProductEntity>>(
              this,
              Invocation.method(
                #getAllProducts,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.ProductEntity>>>);
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i4.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.ProductModel> getCurrentProduct(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentProduct,
          [productId],
        ),
        returnValue: _i9.Future<_i3.ProductModel>.value(_FakeProductModel_1(
          this,
          Invocation.method(
            #getCurrentProduct,
            [productId],
          ),
        )),
      ) as _i9.Future<_i3.ProductModel>);

  @override
  _i9.Future<void> addProduct(_i11.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [product],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteProduct(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> editProduct(_i11.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProduct,
          [product],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.ProductModel>> getAllProducts() => (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
        ),
        returnValue:
            _i9.Future<List<_i3.ProductModel>>.value(<_i3.ProductModel>[]),
      ) as _i9.Future<List<_i3.ProductModel>>);
}

/// A class which mocks [ProductLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i5.ProductLocalDataSource {
  MockProductLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i3.ProductModel>> getAllProducts() => (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
        ),
        returnValue:
            _i9.Future<List<_i3.ProductModel>>.value(<_i3.ProductModel>[]),
      ) as _i9.Future<List<_i3.ProductModel>>);

  @override
  _i9.Future<void> cacheAllProducts(List<_i3.ProductModel>? producToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAllProducts,
          [producToCache],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
}

/// A class which mocks [ProductRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepositoryImpl extends _i1.Mock
    implements _i12.ProductRepositoryImpl {
  MockProductRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ProductRemoteDataSource get productRemoteDataSource =>
      (super.noSuchMethod(
        Invocation.getter(#productRemoteDataSource),
        returnValue: _FakeProductRemoteDataSource_2(
          this,
          Invocation.getter(#productRemoteDataSource),
        ),
      ) as _i4.ProductRemoteDataSource);

  @override
  _i5.ProductLocalDataSource get productLocalDataSource => (super.noSuchMethod(
        Invocation.getter(#productLocalDataSource),
        returnValue: _FakeProductLocalDataSource_3(
          this,
          Invocation.getter(#productLocalDataSource),
        ),
      ) as _i5.ProductLocalDataSource);

  @override
  _i6.NetworkInfo get networkInfo => (super.noSuchMethod(
        Invocation.getter(#networkInfo),
        returnValue: _FakeNetworkInfo_4(
          this,
          Invocation.getter(#networkInfo),
        ),
      ) as _i6.NetworkInfo);

  @override
  _i9.Future<_i2.Either<_i10.Failure, void>> addProduct(
          _i11.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [product],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, void>>.value(
            _FakeEither_0<_i10.Failure, void>(
          this,
          Invocation.method(
            #addProduct,
            [product],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, void>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, void>> deleteProduct(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productId],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, void>>.value(
            _FakeEither_0<_i10.Failure, void>(
          this,
          Invocation.method(
            #deleteProduct,
            [productId],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, void>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, void>> editProduct(
          _i11.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProduct,
          [product],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, void>>.value(
            _FakeEither_0<_i10.Failure, void>(
          this,
          Invocation.method(
            #editProduct,
            [product],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, void>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.ProductEntity>>>
      getAllProducts() => (super.noSuchMethod(
            Invocation.method(
              #getAllProducts,
              [],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure, List<_i11.ProductEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.ProductEntity>>(
              this,
              Invocation.method(
                #getAllProducts,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.ProductEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>> getCurrentProduct(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentProduct,
          [productId],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>>.value(
                _FakeEither_0<_i10.Failure, _i11.ProductEntity>(
          this,
          Invocation.method(
            #getCurrentProduct,
            [productId],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i7.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i15.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i15.Uint8List>.value(_i15.Uint8List(0)),
      ) as _i9.Future<_i15.Uint8List>);

  @override
  _i9.Future<_i7.StreamedResponse> send(_i7.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i9.Future<_i7.StreamedResponse>.value(_FakeStreamedResponse_6(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i9.Future<_i7.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
